### ISSUE TITLE
How do I change the theme color?

### ISSUE THREAD

**Issue by AlisonYoon** [secondstreet/ember-material-components-web#1]
Hi, thanks for this awesome open source.
I have a question. I'm using textfield component now and
I'd like to change the` var(--mdc-theme-primary,#color)`.
I found all the hex color code in vender.css file but it still doesn't show as the color I changed.
I think I need to change it in the js file but I don't know which file to touch.
Could anyone help with this issue?

**Comment by Kerrick** [comment]
Rather than changing the hex color code in vendor.css or in a JS file, you should be able to add the following [CSS custom property](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) to your Ember CLI's `app/sytles/app.css` file:

```css
:root {
  --mdc-theme-primary: #93E1D8;
}
```

You can also override [the other CSS custom properties that Material Components Web uses](https://material.io/components/web/catalog/theme/#css-custom-properties) if you'd like to change other colors used in theming the addon.

Try that out, and let us know if it works.

**Comment by Kerrick** [comment]
I've created an issue at #14 to document this to make it easier to find, too.

**Comment by AlisonYoon** [comment]
Thanks a lot !!
