### ISSUE TITLE
unnecessary event attachments

### ISSUE THREAD

**Issue by JackCA** [secondstreet/ember-material-components-web#22]
I believe that [this line](https://github.com/secondstreet/ember-material-components-web/blob/66778ba2b4e3bdd567a1ae73c2c668b5d7878fe2/addon/mixins/mdc-component.js#L59) is called unnecessarily when the contents of the component change, rather just when the component is initially rendered. Would it be more appropriate in a `didInsertElement` and a `scheduleOnce('afterRender', ...`?

**Comment by Kerrick** [comment]
Good catch! You're correct that that `_attachMdcInteractionHandlers` will indeed run every time the components change, since [didRender happens on re-render as well as initial render](https://guides.emberjs.com/v2.14.0/components/the-component-lifecycle/). Whoops!

Luckily, [the actual event listeners shouldn't be attaching twice](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Multiple_identical_event_listeners). Since they're registered on the same target with the same parameters, the duplicates are discarded.

So it's not _as big_ of an issue as it may sound at first glance, since only one copy of each event handler ends up being attached -- but the iteration through `mdcInteractionHandlers` and the _attempt_ to re-attach are definitely unnecessary hits to performance.

Definitely up for merging a PR to fix this if one comes along! :+1:

**Comment by Kerrick** [comment]
Actually I just took a closer look at that Mixin -- it turns out that we're calling `_detachMdcInteractionHandlers` in `didUpdateAttrs` (which is called on re-render but _not_ on initial render), specifically to avoid this problem -- it detaches the event handlers so they won't be re-attached. But it turns out that doing it that way is unnecessary because the DOM won't attach duplicate handlers, and _doubles_ the array-iteration performance problem -- and adds the actual weight of detaching and re-attaching.

So one possible fix is to remove the `_detachMdcInteractionHandlers` call from `didUpdateAttrs` to reduce the performance problem to the thing I initially thought it was, or to do what you suggested and eliminate both problems at once.

**Comment by JackCA** [comment]
@Kerrick thanks for such a thorough investigation!

Yes, I should have clarified that I didn't notice any direct user-facing bugs per-se, but the way I did find out this was happening was through a performance audit: I have a button that on a regular basis has a child that re-renders, which I believes triggers this parent `render`. 

I think you have a better understanding of the trade-offs between the proposed solutions, so I'll defer that to you!
