### ISSUE TITLE
Proper use of {{mdc-tab-bar}} is not documented. 

### ISSUE THREAD

**Issue by Disorder316** [secondstreet/ember-material-components-web#23]
Currently calling:

{{#mdc-tab-bar}}
  {{#link-to 'xxxx'}}
    page
  {{/link-to}}
  {{#link-to 'xxxx'}}
   page
  {{/link-to}}
{{/mdc-tab-bar}}

This returns a nav bar with 'mdc-tab-bar-upgraded' by default, but the js never activates. The proper usage of this component isn't well documented, could use some thoughts.

**Comment by Kerrick** [comment]
You're right, our documentation needs to improve significantly (#10, #12). PRs graciously accepted, if you have the time.

---

In order to use mdc-tab-bar with its tabs acting as `{{link-to}}`s, you'll want to use its yielded `{{tab}}` components, which extend the `{{link-to}}` component by default.

Example:

```hbs
{{#mdc-tab-bar as |bar|}}
  {{#bar.tab "index"}}
    Home
  {{/bar.tab}}
  {{#bar.tab "other-route"}}
    Elsewhere
  {{/bar.tab}}
{{/mdc-tab-bar}}
```

You can see this in action [in our demo](https://github.com/secondstreet/ember-material-components-web/blob/8a89ddd74f6b793db739632c24b9f2809b19170c/tests/dummy/app/templates/application.hbs#L265-L279) as well.

**Comment by Disorder316** [comment]
Thanks answer is perfect. Works great. Will add any documentation I can if I find the time.
